name: bdms_nest

services:
  postgres:
    image: postgres:15
    container_name: bdms_db
    environment:
      POSTGRES_DB: bdms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bdms_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  bdms_postgres_data:
